- name: Web Server Setup
  hosts: web
  remote_user: root
  tasks:

  - name: Check Distribution
    fail:
      msg: The operating system is not on Debian bullseye.
    when: ansible_distribution != 'Debian' and ansible_distribution_release != 'bullseye'
  
  - name: "Install ansible python3 mysql dependency"
    apt:
      name: python3-mysqldb
      state: latest

  - name: Install nginx
    apt: name=nginx

  - name: Install requirement for php8
    apt:
      pkg:
        - ca-certificates
        - apt-transport-https
        - software-properties-common
        - lsb-release


  - name: Install Git
    apt: name=git

  - name: Install Curl
    apt: name=curl

  - name: install sudo
    apt: name=sudo

  - name: Install Wget
    apt: name=wget 

 

  - name: Install MariaDb
    apt: name={{item}}
    with_items:
      - mariadb-client
      - mariadb-server
      - mariadb-common

  - name: Start MariaDB
    service: name=mysql state=started

  - name: Create app database
    mysql_db:
      name: salsifit
      login_user: root
      login_password:

  - name: Create app user database
    mysql_user:
      name: provencal
      password: legaulois
      priv: salsifit.*:ALL
      login_user: root
      login_password:

  - name: add php8 repo
    shell:
      cmd: wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg && echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list

  - name: Update && Upgrade
    become: true
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install Php8 & symfony package
    apt:
      pkg:
        - php8.0
        - php8.0-fpm
        - php8.0-mysql
        - php8.0-curl
        - php8.0-mbstring
        - php8.0-xml
        - php8.0-zip
        - php8.0-cli
        - php8.0-common
        - php-mysql
        - php8.0-bcmath
        - php-json
        - php-xml
        - php-curl
        - php8.0-cgi
        - php8.0-xsl
        - php8.0-cgi
        - php8.0-gd
        - php8.0-xmlrpc
        - php8.0-soap
        - php8.0-intl

  - name: Copy Nginx Config
    copy:
      src: ./app/nginx/default
      dest: /etc/nginx/sites-enabled/

  - name: Start nginx
    service:
      name: nginx
      state: restarted

  - name: Copy app into /var/www/
    become: yes
    become_user: user
    become_method: su
    synchronize:
      src: ./app
      dest: /var/www/
      rsync_opts:
        - "--no-motd"
        - "--exclude=vendor/"
        - "--exclude=nginx/"
        - "--exclude=.git/"

  - name: Set composer
    shell:
      cmd: mv /var/www/app/composer.phar /usr/bin/composer && chmod 755 /usr/bin/composer

  - name: Install dependancies
    become: yes
    become_user: user
    become_method: su
    shell:
      cmd: composer update && composer install
      chdir: /var/www/app/

  - name: Make migration
    shell:
      cmd: php /var/www/app/bin/console doctrine:migrations:migrate --no-interaction

